[package]
name = "pbdecoder"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1"

[features]
default = ["serialize"]
serialize = ["serde"]
